runtime: php
env: flex
runtime_config:
  document_root: .

# Assuming PHP 7.4
runtime_config:
  php_version: 7.4

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Setting up automatic scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "admin123"
  MYSQL_DSN: "mysql:dbname=zoodb-uma3380;unix_socket=/cloudsql/bubbly-domain-420411:us-south1:zoodb-uma3380"
